// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

import UIKit

// MARK: - Asset Catalogs

@available(*, deprecated, renamed: "VitaminAsset")
public typealias VitaminImageAsset = VitaminAsset

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
extension Vitamix {
  public enum Fill {
    public enum Buildings {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.homeFill instead")
      public static let home = Vitamix.homeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.storeFill instead")
      public static let store = Vitamix.storeFill
    }
    public enum Business {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.awardFill instead")
      public static let award = Vitamix.awardFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.barChartFill instead")
      public static let barChart = Vitamix.barChartFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarFill instead")
      public static let calendar = Vitamix.calendarFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendar2Fill instead")
      public static let calendar2 = Vitamix.calendar2Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarCheckFill instead")
      public static let calendarCheck = Vitamix.calendarCheckFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarDateFill instead")
      public static let calendarDate = Vitamix.calendarDateFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lineChartFill instead")
      public static let lineChart = Vitamix.lineChartFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mailFill instead")
      public static let mail = Vitamix.mailFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mailSendFill instead")
      public static let mailSend = Vitamix.mailSendFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pieChartFill instead")
      public static let pieChart = Vitamix.pieChartFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.printerFill instead")
      public static let printer = Vitamix.printerFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sendPlane2Fill instead")
      public static let sendPlane2 = Vitamix.sendPlane2Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sendPlaneFill instead")
      public static let sendPlane = Vitamix.sendPlaneFill
    }
    public enum Communication {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.feedbackFill instead")
      public static let feedback = Vitamix.feedbackFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.messageFill instead")
      public static let message = Vitamix.messageFill
    }
    public enum Design {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.editFill instead")
      public static let edit = Vitamix.editFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.focusFill instead")
      public static let focus = Vitamix.focusFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.gridFill instead")
      public static let grid = Vitamix.gridFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rulerFill instead")
      public static let ruler = Vitamix.rulerFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.toolsFill instead")
      public static let tools = Vitamix.toolsFill
    }
    public enum Device {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.barcodeFill instead")
      public static let barcode = Vitamix.barcodeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.databaseFill instead")
      public static let database = Vitamix.databaseFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.macFill instead")
      public static let mac = Vitamix.macFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.macbookFill instead")
      public static let macbook = Vitamix.macbookFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.phoneFill instead")
      public static let phone = Vitamix.phoneFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.qrScanFill instead")
      public static let qrScan = Vitamix.qrScanFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rssFill instead")
      public static let rss = Vitamix.rssFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shutDownFill instead")
      public static let shutdown = Vitamix.shutDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.smartphoneFill instead")
      public static let smartphone = Vitamix.smartphoneFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tabletFill instead")
      public static let tablet = Vitamix.tabletFill
    }
    public enum Documents {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.billFill instead")
      public static let bill = Vitamix.billFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fileFill instead")
      public static let file = Vitamix.fileFill
    }
    public enum Editor {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.attachmentFill instead")
      public static let attachment = Vitamix.attachmentFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.linkFill instead")
      public static let link = Vitamix.linkFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.listCheckFill instead")
      public static let listCheck = Vitamix.listCheckFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.unlinkFill instead")
      public static let unlink = Vitamix.unlinkFill
    }
    public enum Finance {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.bankCardFill instead")
      public static let bankCard = Vitamix.bankCardFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.exchangeFill instead")
      public static let exchange = Vitamix.exchangeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.giftFill instead")
      public static let gift = Vitamix.giftFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mastercardFill instead")
      public static let mastercard = Vitamix.mastercardFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyCnyBoxFill instead")
      public static let moneyCnyBox = Vitamix.moneyCnyBoxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyDollarBoxFill instead")
      public static let moneyDollarBox = Vitamix.moneyDollarBoxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyEuroBoxFill instead")
      public static let moneyEuroBox = Vitamix.moneyEuroBoxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyPoundBoxFill instead")
      public static let moneyPoundBox = Vitamix.moneyPoundBoxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.priceTagFill instead")
      public static let priceTag = Vitamix.priceTagFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.refundFill instead")
      public static let refund = Vitamix.refundFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.returnFill instead")
      public static let `return` = Vitamix.returnFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.securePaymentFill instead")
      public static let securePayment = Vitamix.securePaymentFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shoppingBagFill instead")
      public static let shoppingBag = Vitamix.shoppingBagFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shoppingCartFill instead")
      public static let shoppingCart = Vitamix.shoppingCartFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.trophyFill instead")
      public static let trophy = Vitamix.trophyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.visaFill instead")
      public static let visa = Vitamix.visaFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.walletFill instead")
      public static let wallet = Vitamix.walletFill
    }
    public enum Health {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.heartFill instead")
      public static let heart = Vitamix.heartFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.heartPulseFill instead")
      public static let heartPulse = Vitamix.heartPulseFill
    }
    public enum Logos {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.amazonFill instead")
      public static let amazon = Vitamix.amazonFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.androidFill instead")
      public static let android = Vitamix.androidFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.appleFill instead")
      public static let apple = Vitamix.appleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chromeFill instead")
      public static let chrome = Vitamix.chromeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.driveFill instead")
      public static let drive = Vitamix.driveFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.facebookFill instead")
      public static let facebook = Vitamix.facebookFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.firefoxFill instead")
      public static let firefox = Vitamix.firefoxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.githubFill instead")
      public static let github = Vitamix.githubFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.googleFill instead")
      public static let google = Vitamix.googleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.ieFill instead")
      public static let ie = Vitamix.ieFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.instagramFill instead")
      public static let instagram = Vitamix.instagramFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.kakaoTalkFill instead")
      public static let kakaoTalk = Vitamix.kakaoTalkFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lineFill instead")
      public static let line = Vitamix.lineFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.messengerFill instead")
      public static let messenger = Vitamix.messengerFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.naverFill instead")
      public static let naver = Vitamix.naverFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pinterestFill instead")
      public static let pinterest = Vitamix.pinterestFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.safariFill instead")
      public static let safari = Vitamix.safariFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.slackFill instead")
      public static let slack = Vitamix.slackFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.snapchatFill instead")
      public static let snapchat = Vitamix.snapchatFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.telegramFill instead")
      public static let telegram = Vitamix.telegramFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tiktokFill instead")
      public static let tiktok = Vitamix.tiktokFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.twitterFill instead")
      public static let twitter = Vitamix.twitterFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.viberFill instead")
      public static let viber = Vitamix.viberFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.whatsappFill instead")
      public static let whatsapp = Vitamix.whatsappFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.youtubeFill instead")
      public static let youtube = Vitamix.youtubeFill
    }
    public enum Map {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.carFill instead")
      public static let car = Vitamix.carFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.directionFill instead")
      public static let direction = Vitamix.directionFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.distanceFill instead")
      public static let distance = Vitamix.distanceFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.earthFill instead")
      public static let earth = Vitamix.earthFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mapPinFill instead")
      public static let mapPin = Vitamix.mapPinFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.navigationFill instead")
      public static let navigation = Vitamix.navigationFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.ridingFill instead")
      public static let riding = Vitamix.ridingFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rocketFill instead")
      public static let rocket = Vitamix.rocketFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.runFill instead")
      public static let run = Vitamix.runFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.suitcaseFill instead")
      public static let suitcase = Vitamix.suitcaseFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.trainFill instead")
      public static let train = Vitamix.trainFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.truckFill instead")
      public static let truck = Vitamix.truckFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.walkFill instead")
      public static let walk = Vitamix.walkFill
    }
    public enum Media {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cameraFill instead")
      public static let camera = Vitamix.cameraFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.equalizerFill instead")
      public static let equalizer = Vitamix.equalizerFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filmFill instead")
      public static let film = Vitamix.filmFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fullscreenFill instead")
      public static let fullscreen = Vitamix.fullscreenFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.imageFill instead")
      public static let image = Vitamix.imageFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.micFill instead")
      public static let mic = Vitamix.micFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.musicFill instead")
      public static let music = Vitamix.musicFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.music2Fill instead")
      public static let music2 = Vitamix.music2Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.notificationFill instead")
      public static let notification = Vitamix.notificationFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pauseFill instead")
      public static let pause = Vitamix.pauseFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pauseCircleFill instead")
      public static let pauseCircle = Vitamix.pauseCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.playFill instead")
      public static let play = Vitamix.playFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.playCircleFill instead")
      public static let playCircle = Vitamix.playCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.repeatFill instead")
      public static let `repeat` = Vitamix.repeatFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.stopFill instead")
      public static let stop = Vitamix.stopFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.stopCircleFill instead")
      public static let stopCircle = Vitamix.stopCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeAlertFill instead")
      public static let volumeAlert = Vitamix.volumeAlertFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeDownFill instead")
      public static let volumeDown = Vitamix.volumeDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeMuteFill instead")
      public static let volumeMute = Vitamix.volumeMuteFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeUpFill instead")
      public static let volumeUp = Vitamix.volumeUpFill
    }
    public enum Others {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.footballFill instead")
      public static let football = Vitamix.footballFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.hourglassFill instead")
      public static let hourglass = Vitamix.hourglassFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.leafFill instead")
      public static let leaf = Vitamix.leafFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lightbulbFill instead")
      public static let lightbulb = Vitamix.lightbulbFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.recycleFill instead")
      public static let recycle = Vitamix.recycleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.scalesFill instead")
      public static let scales = Vitamix.scalesFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed1Fill instead")
      public static let seed1 = Vitamix.seed1Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed2Fill instead")
      public static let seed2 = Vitamix.seed2Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed3Fill instead")
      public static let seed3 = Vitamix.seed3Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sparklesFill instead")
      public static let sparkles = Vitamix.sparklesFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tShirtFill instead")
      public static let tShirt = Vitamix.tShirtFill
    }
    public enum Services {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.customerServiceFill instead")
      public static let customerService = Vitamix.customerServiceFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.selectedByDecathlonFill instead")
      public static let selectedByDecathlon = Vitamix.selectedByDecathlonFill
    }
    public enum System {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.addCircleFill instead")
      public static let addCircle = Vitamix.addCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.addFill instead")
      public static let add = Vitamix.addFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.alertFill instead")
      public static let alert = Vitamix.alertFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownFill instead")
      public static let arrowDown = Vitamix.arrowDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownCircleFill instead")
      public static let arrowDownCircle = Vitamix.arrowDownCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronDownFill instead")
      public static let arrowDownS = Vitamix.chevronDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownFill instead")
      public static let arrowDropDown = Vitamix.arrowDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftFill instead")
      public static let arrowDropLeft = Vitamix.arrowLeftFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightFill instead")
      public static let arrowDropRight = Vitamix.arrowRightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpFill instead")
      public static let arrowDropUp = Vitamix.arrowUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowGoBackFill instead")
      public static let arrowGoBack = Vitamix.arrowGoBackFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowGoForwardFill instead")
      public static let arrowGoForward = Vitamix.arrowGoForwardFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftFill instead")
      public static let arrowLeft = Vitamix.arrowLeftFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftCircleFill instead")
      public static let arrowLeftCircle = Vitamix.arrowLeftCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftDownFill instead")
      public static let arrowLeftDown = Vitamix.arrowLeftDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftRightFill instead")
      public static let arrowLeftRight = Vitamix.arrowLeftRightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronLeftFill instead")
      public static let arrowLeftS = Vitamix.chevronLeftFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftUpFill instead")
      public static let arrowLeftUp = Vitamix.arrowLeftUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightFill instead")
      public static let arrowRight = Vitamix.arrowRightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightCircleFill instead")
      public static let arrowRightCircle = Vitamix.arrowRightCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightDownFill instead")
      public static let arrowRightDown = Vitamix.arrowRightDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronRightFill instead")
      public static let arrowRightS = Vitamix.chevronRightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightUpFill instead")
      public static let arrowRightUp = Vitamix.arrowRightUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpFill instead")
      public static let arrowUp = Vitamix.arrowUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpCircleFill instead")
      public static let arrowUpCircle = Vitamix.arrowUpCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpDownFill instead")
      public static let arrowUpDown = Vitamix.arrowUpDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronUpFill instead")
      public static let arrowUpS = Vitamix.chevronUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkFill instead")
      public static let check = Vitamix.checkFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxFill instead")
      public static let checkbox = Vitamix.checkboxFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxBlankFill instead")
      public static let checkboxBlank = Vitamix.checkboxBlankFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxBlankCircleFill instead")
      public static let checkboxBlankCircle = Vitamix.checkboxBlankCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxCircleFill instead")
      public static let checkboxCircle = Vitamix.checkboxCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxMultipleFill instead")
      public static let checkboxMultiple = Vitamix.checkboxMultipleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronDownFill instead")
      public static let chevronDown = Vitamix.chevronDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronLeftFill instead")
      public static let chevronLeft = Vitamix.chevronLeftFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronRightFill instead")
      public static let chevronRight = Vitamix.chevronRightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronUpFill instead")
      public static let chevronUp = Vitamix.chevronUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.closeFill instead")
      public static let close = Vitamix.closeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.closeCircleFill instead")
      public static let closeCircle = Vitamix.closeCircleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.counterFill instead")
      public static let counter = Vitamix.counterFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.deleteBinFill instead")
      public static let deleteBin = Vitamix.deleteBinFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.downloadFill instead")
      public static let download = Vitamix.downloadFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.errorWarningFill instead")
      public static let errorWarning = Vitamix.errorWarningFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.externalLinkFill instead")
      public static let externalLink = Vitamix.externalLinkFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.eyeFill instead")
      public static let eye = Vitamix.eyeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.eyeOffFill instead")
      public static let eyeOff = Vitamix.eyeOffFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fileCopyFill instead")
      public static let fileCopy = Vitamix.fileCopyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filterFill instead")
      public static let filter = Vitamix.filterFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filterOffFill instead")
      public static let filterOff = Vitamix.filterOffFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.forbidFill instead")
      public static let forbid = Vitamix.forbidFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.functionFill instead")
      public static let function = Vitamix.functionFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.historyFill instead")
      public static let history = Vitamix.historyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.informationFill instead")
      public static let information = Vitamix.informationFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.listSettingsFill instead")
      public static let listSettings = Vitamix.listSettingsFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lockFill instead")
      public static let lock = Vitamix.lockFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.logoutFill instead")
      public static let logout = Vitamix.logoutFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.menuFill instead")
      public static let menu = Vitamix.menuFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moreFill instead")
      public static let more = Vitamix.moreFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.more2Fill instead")
      public static let more2 = Vitamix.more2Fill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.packageFill instead")
      public static let package = Vitamix.packageFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.questionFill instead")
      public static let question = Vitamix.questionFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.radioButtonFill instead")
      public static let radioButton = Vitamix.radioButtonFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.refreshFill instead")
      public static let refresh = Vitamix.refreshFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.searchFill instead")
      public static let search = Vitamix.searchFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.settingsFill instead")
      public static let settings = Vitamix.settingsFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareAndroidFill instead")
      public static let shareAndroid = Vitamix.shareAndroidFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareIosFill instead")
      public static let shareIos = Vitamix.shareIosFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareFill instead")
      public static let share = Vitamix.shareFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shieldCheckFill instead")
      public static let shieldCheck = Vitamix.shieldCheckFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.starFill instead")
      public static let star = Vitamix.starFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.starHalfFill instead")
      public static let starHalf = Vitamix.starHalfFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.subtractFill instead")
      public static let subtract = Vitamix.subtractFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thumbDownFill instead")
      public static let thumbDown = Vitamix.thumbDownFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thumbUpFill instead")
      public static let thumbUp = Vitamix.thumbUpFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.timeFill instead")
      public static let time = Vitamix.timeFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.timerFill instead")
      public static let timer = Vitamix.timerFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.uploadFill instead")
      public static let upload = Vitamix.uploadFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.zoomInFill instead")
      public static let zoomIn = Vitamix.zoomInFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.zoomOutFill instead")
      public static let zoomOut = Vitamix.zoomOutFill
    }
    public enum Tasks {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.taskFill instead")
      public static let task = Vitamix.taskFill
    }
    public enum User {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.bodyScanFill instead")
      public static let bodyScan = Vitamix.bodyScanFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionFill instead")
      public static let emotion = Vitamix.emotionFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionLaughFill instead")
      public static let emotionLaugh = Vitamix.emotionLaughFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionNormalFill instead")
      public static let emotionNormal = Vitamix.emotionNormalFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionSadFill instead")
      public static let emotionSad = Vitamix.emotionSadFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionUnhappyFill instead")
      public static let emotionUnhappy = Vitamix.emotionUnhappyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.groupFill instead")
      public static let group = Vitamix.groupFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.userFill instead")
      public static let user = Vitamix.userFill
    }
    public enum Weather {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cloudFill instead")
      public static let cloud = Vitamix.cloudFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cloudWindyFill instead")
      public static let cloudWindy = Vitamix.cloudWindyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.drizzleFill instead")
      public static let drizzle = Vitamix.drizzleFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fireFill instead")
      public static let fire = Vitamix.fireFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.flashlightFill instead")
      public static let flashlight = Vitamix.flashlightFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.foggyFill instead")
      public static let foggy = Vitamix.foggyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.hailFill instead")
      public static let hail = Vitamix.hailFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mistFill instead")
      public static let mist = Vitamix.mistFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moonFill instead")
      public static let moon = Vitamix.moonFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moonCloudyFill instead")
      public static let moonCloudy = Vitamix.moonCloudyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rainyFill instead")
      public static let rainy = Vitamix.rainyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.showersFill instead")
      public static let showers = Vitamix.showersFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.snowyFill instead")
      public static let snowy = Vitamix.snowyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sunFill instead")
      public static let sun = Vitamix.sunFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sunCloudyFill instead")
      public static let sunCloudy = Vitamix.sunCloudyFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tempColdFill instead")
      public static let tempCold = Vitamix.tempColdFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tempHotFill instead")
      public static let tempHot = Vitamix.tempHotFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thunderstormsFill instead")
      public static let thunderstorms = Vitamix.thunderstormsFill
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.windyFill instead")
      public static let windy = Vitamix.windyFill
    }
  }
  public enum Line {
    public enum Buildings {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.homeLine instead")
      public static let home = Vitamix.homeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.storeLine instead")
      public static let store = Vitamix.storeLine
    }
    public enum Business {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.awardLine instead")
      public static let award = Vitamix.awardLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.barChartLine instead")
      public static let barChart = Vitamix.barChartLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarLine instead")
      public static let calendar = Vitamix.calendarLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendar2Line instead")
      public static let calendar2 = Vitamix.calendar2Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarCheckLine instead")
      public static let calendarCheck = Vitamix.calendarCheckLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.calendarDateLine instead")
      public static let calendarDate = Vitamix.calendarDateLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lineChartLine instead")
      public static let lineChart = Vitamix.lineChartLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mailLine instead")
      public static let mail = Vitamix.mailLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mailSendLine instead")
      public static let mailSend = Vitamix.mailSendLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pieChartLine instead")
      public static let pieChart = Vitamix.pieChartLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.printerLine instead")
      public static let printer = Vitamix.printerLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sendPlane2Line instead")
      public static let sendPlane2 = Vitamix.sendPlane2Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sendPlaneLine instead")
      public static let sendPlane = Vitamix.sendPlaneLine
    }
    public enum Communication {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.feedbackLine instead")
      public static let feedback = Vitamix.feedbackLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.messageLine instead")
      public static let message = Vitamix.messageLine
    }
    public enum Design {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.editLine instead")
      public static let edit = Vitamix.editLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.focusLine instead")
      public static let focus = Vitamix.focusLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.gridLine instead")
      public static let grid = Vitamix.gridLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rulerLine instead")
      public static let ruler = Vitamix.rulerLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.toolsLine instead")
      public static let tools = Vitamix.toolsLine
    }
    public enum Device {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.barcodeLine instead")
      public static let barcode = Vitamix.barcodeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.databaseLine instead")
      public static let database = Vitamix.databaseLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.macLine instead")
      public static let mac = Vitamix.macLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.macbookLine instead")
      public static let macbook = Vitamix.macbookLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.phoneLine instead")
      public static let phone = Vitamix.phoneLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.qrScanLine instead")
      public static let qrScan = Vitamix.qrScanLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rssLine instead")
      public static let rss = Vitamix.rssLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shutDownLine instead")
      public static let shutdown = Vitamix.shutDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.smartphoneLine instead")
      public static let smartphone = Vitamix.smartphoneLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tabletLine instead")
      public static let tablet = Vitamix.tabletLine
    }
    public enum Documents {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.billLine instead")
      public static let bill = Vitamix.billLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fileLine instead")
      public static let file = Vitamix.fileLine
    }
    public enum Editor {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.attachmentLine instead")
      public static let attachment = Vitamix.attachmentLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.linkLine instead")
      public static let link = Vitamix.linkLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.listCheckLine instead")
      public static let listCheck = Vitamix.listCheckLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.unlinkLine instead")
      public static let unlink = Vitamix.unlinkLine
    }
    public enum Finance {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.bankCardLine instead")
      public static let bankCard = Vitamix.bankCardLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.exchangeLine instead")
      public static let exchange = Vitamix.exchangeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.giftLine instead")
      public static let gift = Vitamix.giftLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mastercardLine instead")
      public static let mastercard = Vitamix.mastercardLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyCnyBoxLine instead")
      public static let moneyCnyBox = Vitamix.moneyCnyBoxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyDollarBoxLine instead")
      public static let moneyDollarBox = Vitamix.moneyDollarBoxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyEuroBoxLine instead")
      public static let moneyEuroBox = Vitamix.moneyEuroBoxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moneyPoundBoxLine instead")
      public static let moneyPoundBox = Vitamix.moneyPoundBoxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.priceTagLine instead")
      public static let priceTag = Vitamix.priceTagLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.refundLine instead")
      public static let refund = Vitamix.refundLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.returnLine instead")
      public static let `return` = Vitamix.returnLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.securePaymentLine instead")
      public static let securePayment = Vitamix.securePaymentLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shoppingBagLine instead")
      public static let shoppingBag = Vitamix.shoppingBagLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shoppingCartLine instead")
      public static let shoppingCart = Vitamix.shoppingCartLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.trophyLine instead")
      public static let trophy = Vitamix.trophyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.visaLine instead")
      public static let visa = Vitamix.visaLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.walletLine instead")
      public static let wallet = Vitamix.walletLine
    }
    public enum Health {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.heartLine instead")
      public static let heart = Vitamix.heartLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.heartPulseLine instead")
      public static let heartPulse = Vitamix.heartPulseLine
    }
    public enum Logos {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.amazonLine instead")
      public static let amazon = Vitamix.amazonLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.androidLine instead")
      public static let android = Vitamix.androidLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.appleLine instead")
      public static let apple = Vitamix.appleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chromeLine instead")
      public static let chrome = Vitamix.chromeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.driveLine instead")
      public static let drive = Vitamix.driveLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.facebookLine instead")
      public static let facebook = Vitamix.facebookLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.firefoxLine instead")
      public static let firefox = Vitamix.firefoxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.githubLine instead")
      public static let github = Vitamix.githubLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.googleLine instead")
      public static let google = Vitamix.googleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.ieLine instead")
      public static let ie = Vitamix.ieLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.instagramLine instead")
      public static let instagram = Vitamix.instagramLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.kakaoTalkLine instead")
      public static let kakaoTalk = Vitamix.kakaoTalkLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lineLine instead")
      public static let line = Vitamix.lineLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.messengerLine instead")
      public static let messenger = Vitamix.messengerLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.naverLine instead")
      public static let naver = Vitamix.naverLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pinterestLine instead")
      public static let pinterest = Vitamix.pinterestLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.safariLine instead")
      public static let safari = Vitamix.safariLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.slackLine instead")
      public static let slack = Vitamix.slackLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.snapchatLine instead")
      public static let snapchat = Vitamix.snapchatLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.telegramLine instead")
      public static let telegram = Vitamix.telegramLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tiktokLine instead")
      public static let tiktok = Vitamix.tiktokLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.twitterLine instead")
      public static let twitter = Vitamix.twitterLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.viberLine instead")
      public static let viber = Vitamix.viberLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.whatsappLine instead")
      public static let whatsapp = Vitamix.whatsappLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.youtubeLine instead")
      public static let youtube = Vitamix.youtubeLine
    }
    public enum Map {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.carLine instead")
      public static let car = Vitamix.carLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.directionLine instead")
      public static let direction = Vitamix.directionLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.distanceLine instead")
      public static let distance = Vitamix.distanceLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.earthLine instead")
      public static let earth = Vitamix.earthLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mapPinLine instead")
      public static let mapPin = Vitamix.mapPinLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.navigationLine instead")
      public static let navigation = Vitamix.navigationLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.ridingLine instead")
      public static let riding = Vitamix.ridingLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rocketLine instead")
      public static let rocket = Vitamix.rocketLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.runLine instead")
      public static let run = Vitamix.runLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.suitcaseLine instead")
      public static let suitcase = Vitamix.suitcaseLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.trainLine instead")
      public static let train = Vitamix.trainLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.truckLine instead")
      public static let truck = Vitamix.truckLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.walkLine instead")
      public static let walk = Vitamix.walkLine
    }
    public enum Media {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cameraLine instead")
      public static let camera = Vitamix.cameraLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.equalizerLine instead")
      public static let equalizer = Vitamix.equalizerLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filmLine instead")
      public static let film = Vitamix.filmLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fullscreenLine instead")
      public static let fullscreen = Vitamix.fullscreenLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.imageLine instead")
      public static let image = Vitamix.imageLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.micLine instead")
      public static let mic = Vitamix.micLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.musicLine instead")
      public static let music = Vitamix.musicLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.music2Line instead")
      public static let music2 = Vitamix.music2Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.notificationLine instead")
      public static let notification = Vitamix.notificationLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pauseLine instead")
      public static let pause = Vitamix.pauseLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.pauseCircleLine instead")
      public static let pauseCircle = Vitamix.pauseCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.playLine instead")
      public static let play = Vitamix.playLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.playCircleLine instead")
      public static let playCircle = Vitamix.playCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.repeatLine instead")
      public static let `repeat` = Vitamix.repeatLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.stopLine instead")
      public static let stop = Vitamix.stopLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.stopCircleLine instead")
      public static let stopCircle = Vitamix.stopCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeAlertLine instead")
      public static let volumeAlert = Vitamix.volumeAlertLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeDownLine instead")
      public static let volumeDown = Vitamix.volumeDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeMuteLine instead")
      public static let volumeMute = Vitamix.volumeMuteLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.volumeUpLine instead")
      public static let volumeUp = Vitamix.volumeUpLine
    }
    public enum Others {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.footballLine instead")
      public static let football = Vitamix.footballLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.hourglassLine instead")
      public static let hourglass = Vitamix.hourglassLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.leafLine instead")
      public static let leaf = Vitamix.leafLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lightbulbLine instead")
      public static let lightbulb = Vitamix.lightbulbLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.recycleLine instead")
      public static let recycle = Vitamix.recycleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.scalesLine instead")
      public static let scales = Vitamix.scalesLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed1Line instead")
      public static let seed1 = Vitamix.seed1Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed2Line instead")
      public static let seed2 = Vitamix.seed2Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.seed3Line instead")
      public static let seed3 = Vitamix.seed3Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sparklesLine instead")
      public static let sparkles = Vitamix.sparklesLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tShirtLine instead")
      public static let tShirt = Vitamix.tShirtLine
    }
    public enum Services {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.customerServiceLine instead")
      public static let customerService = Vitamix.customerServiceLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.selectedByDecathlonLine instead")
      public static let selectedByDecathlon = Vitamix.selectedByDecathlonLine
    }
    public enum System {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.addCircleLine instead")
      public static let addCircle = Vitamix.addCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.addLine instead")
      public static let add = Vitamix.addLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.alertLine instead")
      public static let alert = Vitamix.alertLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownLine instead")
      public static let arrowDown = Vitamix.arrowDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownCircleLine instead")
      public static let arrowDownCircle = Vitamix.arrowDownCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronDownLine instead")
      public static let arrowDownS = Vitamix.chevronDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDownLine instead")
      public static let arrowDropDown = Vitamix.arrowDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowDropLeftLine instead")
      public static let arrowDropLeft = Vitamix.arrowLeftLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightLine instead")
      public static let arrowDropRight = Vitamix.arrowRightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpLine instead")
      public static let arrowDropUp = Vitamix.arrowUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowGoBackLine instead")
      public static let arrowGoBack = Vitamix.arrowGoBackLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowGoForwardLine instead")
      public static let arrowGoForward = Vitamix.arrowGoForwardLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftLine instead")
      public static let arrowLeft = Vitamix.arrowLeftLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftCircleLine instead")
      public static let arrowLeftCircle = Vitamix.arrowLeftCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftDownLine instead")
      public static let arrowLeftDown = Vitamix.arrowLeftDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftRightLine instead")
      public static let arrowLeftRight = Vitamix.arrowLeftRightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronLeftLine instead")
      public static let arrowLeftS = Vitamix.chevronLeftLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowLeftUpLine instead")
      public static let arrowLeftUp = Vitamix.arrowLeftUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightLine instead")
      public static let arrowRight = Vitamix.arrowRightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightCircleLine instead")
      public static let arrowRightCircle = Vitamix.arrowRightCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightDownLine instead")
      public static let arrowRightDown = Vitamix.arrowRightDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronRightLine instead")
      public static let arrowRightS = Vitamix.chevronRightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowRightUpLine instead")
      public static let arrowRightUp = Vitamix.arrowRightUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpLine instead")
      public static let arrowUp = Vitamix.arrowUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpCircleLine instead")
      public static let arrowUpCircle = Vitamix.arrowUpCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.arrowUpDownLine instead")
      public static let arrowUpDown = Vitamix.arrowUpDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronUpLine instead")
      public static let arrowUpS = Vitamix.chevronUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkLine instead")
      public static let check = Vitamix.checkLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxLine instead")
      public static let checkbox = Vitamix.checkboxLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxBlankLine instead")
      public static let checkboxBlank = Vitamix.checkboxBlankLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxBlankCircleLine instead")
      public static let checkboxBlankCircle = Vitamix.checkboxBlankCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxCircleLine instead")
      public static let checkboxCircle = Vitamix.checkboxCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.checkboxMultipleLine instead")
      public static let checkboxMultiple = Vitamix.checkboxMultipleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronDownLine instead")
      public static let chevronDown = Vitamix.chevronDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronLeftLine instead")
      public static let chevronLeft = Vitamix.chevronLeftLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronRightLine instead")
      public static let chevronRight = Vitamix.chevronRightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.chevronUpLine instead")
      public static let chevronUp = Vitamix.chevronUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.closeLine instead")
      public static let close = Vitamix.closeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.closeCircleLine instead")
      public static let closeCircle = Vitamix.closeCircleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.counterLine instead")
      public static let counter = Vitamix.counterLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.deleteBinLine instead")
      public static let deleteBin = Vitamix.deleteBinLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.downloadLine instead")
      public static let download = Vitamix.downloadLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.errorWarningLine instead")
      public static let errorWarning = Vitamix.errorWarningLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.externalLinkLine instead")
      public static let externalLink = Vitamix.externalLinkLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.eyeLine instead")
      public static let eye = Vitamix.eyeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.eyeOffLine instead")
      public static let eyeOff = Vitamix.eyeOffLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fileCopyLine instead")
      public static let fileCopy = Vitamix.fileCopyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filterLine instead")
      public static let filter = Vitamix.filterLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.filterOffLine instead")
      public static let filterOff = Vitamix.filterOffLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.forbidLine instead")
      public static let forbid = Vitamix.forbidLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.functionLine instead")
      public static let function = Vitamix.functionLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.historyLine instead")
      public static let history = Vitamix.historyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.informationLine instead")
      public static let information = Vitamix.informationLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.listSettingsLine instead")
      public static let listSettings = Vitamix.listSettingsLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.lockLine instead")
      public static let lock = Vitamix.lockLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.logoutLine instead")
      public static let logout = Vitamix.logoutLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.menuLine instead")
      public static let menu = Vitamix.menuLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moreLine instead")
      public static let more = Vitamix.moreLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.more2Line instead")
      public static let more2 = Vitamix.more2Line
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.packageLine instead")
      public static let package = Vitamix.packageLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.questionLine instead")
      public static let question = Vitamix.questionLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.radioButtonLine instead")
      public static let radioButton = Vitamix.radioButtonLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.refreshLine instead")
      public static let refresh = Vitamix.refreshLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.searchLine instead")
      public static let search = Vitamix.searchLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.settingsLine instead")
      public static let settings = Vitamix.settingsLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareAndroidLine instead")
      public static let shareAndroid = Vitamix.shareAndroidLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareIosLine instead")
      public static let shareIos = Vitamix.shareIosLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shareLine instead")
      public static let share = Vitamix.shareLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.shieldCheckLine instead")
      public static let shieldCheck = Vitamix.shieldCheckLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.starLine instead")
      public static let star = Vitamix.starLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.starHalfLine instead")
      public static let starHalf = Vitamix.starHalfLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.subtractLine instead")
      public static let subtract = Vitamix.subtractLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thumbDownLine instead")
      public static let thumbDown = Vitamix.thumbDownLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thumbUpLine instead")
      public static let thumbUp = Vitamix.thumbUpLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.timeLine instead")
      public static let time = Vitamix.timeLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.timerLine instead")
      public static let timer = Vitamix.timerLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.uploadLine instead")
      public static let upload = Vitamix.uploadLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.zoomInLine instead")
      public static let zoomIn = Vitamix.zoomInLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.zoomOutLine instead")
      public static let zoomOut = Vitamix.zoomOutLine
    }
    public enum Tasks {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.taskLine instead")
      public static let task = Vitamix.taskLine
    }
    public enum User {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.bodyScanLine instead")
      public static let bodyScan = Vitamix.bodyScanLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionLine instead")
      public static let emotion = Vitamix.emotionLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionLaughLine instead")
      public static let emotionLaugh = Vitamix.emotionLaughLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionNormalLine instead")
      public static let emotionNormal = Vitamix.emotionNormalLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionSadLine instead")
      public static let emotionSad = Vitamix.emotionSadLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.emotionUnhappyLine instead")
      public static let emotionUnhappy = Vitamix.emotionUnhappyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.groupLine instead")
      public static let group = Vitamix.groupLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.userLine instead")
      public static let user = Vitamix.userLine
    }
    public enum Weather {
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cloudLine instead")
      public static let cloud = Vitamix.cloudLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.cloudWindyLine instead")
      public static let cloudWindy = Vitamix.cloudWindyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.drizzleLine instead")
      public static let drizzle = Vitamix.drizzleLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.fireLine instead")
      public static let fire = Vitamix.fireLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.flashlightLine instead")
      public static let flashlight = Vitamix.flashlightLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.foggyLine instead")
      public static let foggy = Vitamix.foggyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.hailLine instead")
      public static let hail = Vitamix.hailLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.mistLine instead")
      public static let mist = Vitamix.mistLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moonLine instead")
      public static let moon = Vitamix.moonLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.moonCloudyLine instead")
      public static let moonCloudy = Vitamix.moonCloudyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.rainyLine instead")
      public static let rainy = Vitamix.rainyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.showersLine instead")
      public static let showers = Vitamix.showersLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.snowyLine instead")
      public static let snowy = Vitamix.snowyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sunLine instead")
      public static let sun = Vitamix.sunLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.sunCloudyLine instead")
      public static let sunCloudy = Vitamix.sunCloudyLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tempColdLine instead")
      public static let tempCold = Vitamix.tempColdLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.tempHotLine instead")
      public static let tempHot = Vitamix.tempHotLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.thunderstormsLine instead")
      public static let thunderstorms = Vitamix.thunderstormsLine
      @available(*, deprecated, message: "Use [UI]Image.Vitamix.windyLine instead")
      public static let windy = Vitamix.windyLine
    }
  }
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name
