// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

import UIKit

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
public enum VitaminAssets {
  public enum Flag {
    public static let ad = VitaminAsset(name: "AD")
    public static let ae = VitaminAsset(name: "AE")
    public static let af = VitaminAsset(name: "AF")
    public static let ag = VitaminAsset(name: "AG")
    public static let ai = VitaminAsset(name: "AI")
    public static let al = VitaminAsset(name: "AL")
    public static let am = VitaminAsset(name: "AM")
    public static let an = VitaminAsset(name: "AN")
    public static let ao = VitaminAsset(name: "AO")
    public static let ar = VitaminAsset(name: "AR")
    public static let at = VitaminAsset(name: "AT")
    public static let au = VitaminAsset(name: "AU")
    public static let aw = VitaminAsset(name: "AW")
    public static let ax = VitaminAsset(name: "AX")
    public static let az = VitaminAsset(name: "AZ")
    public static let ba = VitaminAsset(name: "BA")
    public static let bb = VitaminAsset(name: "BB")
    public static let bd = VitaminAsset(name: "BD")
    public static let be = VitaminAsset(name: "BE")
    public static let bf = VitaminAsset(name: "BF")
    public static let bg = VitaminAsset(name: "BG")
    public static let bh = VitaminAsset(name: "BH")
    public static let bi = VitaminAsset(name: "BI")
    public static let bj = VitaminAsset(name: "BJ")
    public static let bm = VitaminAsset(name: "BM")
    public static let bn = VitaminAsset(name: "BN")
    public static let bo = VitaminAsset(name: "BO")
    public static let br = VitaminAsset(name: "BR")
    public static let bs = VitaminAsset(name: "BS")
    public static let bt = VitaminAsset(name: "BT")
    public static let bw = VitaminAsset(name: "BW")
    public static let by = VitaminAsset(name: "BY")
    public static let bz = VitaminAsset(name: "BZ")
    public static let ca = VitaminAsset(name: "CA")
    public static let caf = VitaminAsset(name: "CAF")
    public static let cas = VitaminAsset(name: "CAS")
    public static let cd = VitaminAsset(name: "CD")
    public static let ceu = VitaminAsset(name: "CEU")
    public static let cf = VitaminAsset(name: "CF")
    public static let cg = VitaminAsset(name: "CG")
    public static let ch = VitaminAsset(name: "CH")
    public static let ci = VitaminAsset(name: "CI")
    public static let cl = VitaminAsset(name: "CL")
    public static let cm = VitaminAsset(name: "CM")
    public static let cn = VitaminAsset(name: "CN")
    public static let cna = VitaminAsset(name: "CNA")
    public static let co = VitaminAsset(name: "CO")
    public static let coc = VitaminAsset(name: "COC")
    public static let cr = VitaminAsset(name: "CR")
    public static let csa = VitaminAsset(name: "CSA")
    public static let cu = VitaminAsset(name: "CU")
    public static let cv = VitaminAsset(name: "CV")
    public static let cy = VitaminAsset(name: "CY")
    public static let cz = VitaminAsset(name: "CZ")
    public static let de = VitaminAsset(name: "DE")
    public static let dj = VitaminAsset(name: "DJ")
    public static let dk = VitaminAsset(name: "DK")
    public static let dm = VitaminAsset(name: "DM")
    public static let `do` = VitaminAsset(name: "DO")
    public static let dz = VitaminAsset(name: "DZ")
    public static let ec = VitaminAsset(name: "EC")
    public static let ee = VitaminAsset(name: "EE")
    public static let eg = VitaminAsset(name: "EG")
    public static let er = VitaminAsset(name: "ER")
    public static let es = VitaminAsset(name: "ES")
    public static let et = VitaminAsset(name: "ET")
    public static let eu = VitaminAsset(name: "EU")
    public static let fi = VitaminAsset(name: "FI")
    public static let fj = VitaminAsset(name: "FJ")
    public static let fk = VitaminAsset(name: "FK")
    public static let fm = VitaminAsset(name: "FM")
    public static let fr = VitaminAsset(name: "FR")
    public static let ga = VitaminAsset(name: "GA")
    public static let gb = VitaminAsset(name: "GB")
    public static let gd = VitaminAsset(name: "GD")
    public static let ge = VitaminAsset(name: "GE")
    public static let gg = VitaminAsset(name: "GG")
    public static let gh = VitaminAsset(name: "GH")
    public static let gi = VitaminAsset(name: "GI")
    public static let gm = VitaminAsset(name: "GM")
    public static let gn = VitaminAsset(name: "GN")
    public static let gq = VitaminAsset(name: "GQ")
    public static let gr = VitaminAsset(name: "GR")
    public static let gt = VitaminAsset(name: "GT")
    public static let gw = VitaminAsset(name: "GW")
    public static let gy = VitaminAsset(name: "GY")
    public static let hk = VitaminAsset(name: "HK")
    public static let hn = VitaminAsset(name: "HN")
    public static let hr = VitaminAsset(name: "HR")
    public static let ht = VitaminAsset(name: "HT")
    public static let hu = VitaminAsset(name: "HU")
    public static let id = VitaminAsset(name: "ID")
    public static let ie = VitaminAsset(name: "IE")
    public static let il = VitaminAsset(name: "IL")
    public static let im = VitaminAsset(name: "IM")
    public static let `in` = VitaminAsset(name: "IN")
    public static let iq = VitaminAsset(name: "IQ")
    public static let ir = VitaminAsset(name: "IR")
    public static let `is` = VitaminAsset(name: "IS")
    public static let it = VitaminAsset(name: "IT")
    public static let je = VitaminAsset(name: "JE")
    public static let jm = VitaminAsset(name: "JM")
    public static let jo = VitaminAsset(name: "JO")
    public static let jp = VitaminAsset(name: "JP")
    public static let ke = VitaminAsset(name: "KE")
    public static let kg = VitaminAsset(name: "KG")
    public static let kh = VitaminAsset(name: "KH")
    public static let km = VitaminAsset(name: "KM")
    public static let kn = VitaminAsset(name: "KN")
    public static let kp = VitaminAsset(name: "KP")
    public static let kr = VitaminAsset(name: "KR")
    public static let kw = VitaminAsset(name: "KW")
    public static let ky = VitaminAsset(name: "KY")
    public static let kz = VitaminAsset(name: "KZ")
    public static let la = VitaminAsset(name: "LA")
    public static let lb = VitaminAsset(name: "LB")
    public static let lc = VitaminAsset(name: "LC")
    public static let li = VitaminAsset(name: "LI")
    public static let lk = VitaminAsset(name: "LK")
    public static let lr = VitaminAsset(name: "LR")
    public static let ls = VitaminAsset(name: "LS")
    public static let lt = VitaminAsset(name: "LT")
    public static let lu = VitaminAsset(name: "LU")
    public static let lv = VitaminAsset(name: "LV")
    public static let ly = VitaminAsset(name: "LY")
    public static let ma = VitaminAsset(name: "MA")
    public static let mc = VitaminAsset(name: "MC")
    public static let md = VitaminAsset(name: "MD")
    public static let me = VitaminAsset(name: "ME")
    public static let mg = VitaminAsset(name: "MG")
    public static let mk = VitaminAsset(name: "MK")
    public static let ml = VitaminAsset(name: "ML")
    public static let mm = VitaminAsset(name: "MM")
    public static let mn = VitaminAsset(name: "MN")
    public static let mo = VitaminAsset(name: "MO")
    public static let mr = VitaminAsset(name: "MR")
    public static let ms = VitaminAsset(name: "MS")
    public static let mt = VitaminAsset(name: "MT")
    public static let mu = VitaminAsset(name: "MU")
    public static let mv = VitaminAsset(name: "MV")
    public static let mw = VitaminAsset(name: "MW")
    public static let mx = VitaminAsset(name: "MX")
    public static let my = VitaminAsset(name: "MY")
    public static let mz = VitaminAsset(name: "MZ")
    public static let na = VitaminAsset(name: "NA")
    public static let ne = VitaminAsset(name: "NE")
    public static let ng = VitaminAsset(name: "NG")
    public static let ni = VitaminAsset(name: "NI")
    public static let nl = VitaminAsset(name: "NL")
    public static let no = VitaminAsset(name: "NO")
    public static let np = VitaminAsset(name: "NP")
    public static let nz = VitaminAsset(name: "NZ")
    public static let om = VitaminAsset(name: "OM")
    public static let pa = VitaminAsset(name: "PA")
    public static let pe = VitaminAsset(name: "PE")
    public static let pf = VitaminAsset(name: "PF")
    public static let pg = VitaminAsset(name: "PG")
    public static let ph = VitaminAsset(name: "PH")
    public static let pk = VitaminAsset(name: "PK")
    public static let pl = VitaminAsset(name: "PL")
    public static let pr = VitaminAsset(name: "PR")
    public static let pt = VitaminAsset(name: "PT")
    public static let pw = VitaminAsset(name: "PW")
    public static let py = VitaminAsset(name: "PY")
    public static let qa = VitaminAsset(name: "QA")
    public static let ro = VitaminAsset(name: "RO")
    public static let rs = VitaminAsset(name: "RS")
    public static let ru = VitaminAsset(name: "RU")
    public static let rw = VitaminAsset(name: "RW")
    public static let sa = VitaminAsset(name: "SA")
    public static let sb = VitaminAsset(name: "SB")
    public static let sc = VitaminAsset(name: "SC")
    public static let sd = VitaminAsset(name: "SD")
    public static let se = VitaminAsset(name: "SE")
    public static let sg = VitaminAsset(name: "SG")
    public static let sh = VitaminAsset(name: "SH")
    public static let si = VitaminAsset(name: "SI")
    public static let sk = VitaminAsset(name: "SK")
    public static let sl = VitaminAsset(name: "SL")
    public static let sm = VitaminAsset(name: "SM")
    public static let sn = VitaminAsset(name: "SN")
    public static let so = VitaminAsset(name: "SO")
    public static let sr = VitaminAsset(name: "SR")
    public static let st = VitaminAsset(name: "ST")
    public static let sv = VitaminAsset(name: "SV")
    public static let sy = VitaminAsset(name: "SY")
    public static let sz = VitaminAsset(name: "SZ")
    public static let tc = VitaminAsset(name: "TC")
    public static let td = VitaminAsset(name: "TD")
    public static let tg = VitaminAsset(name: "TG")
    public static let th = VitaminAsset(name: "TH")
    public static let tj = VitaminAsset(name: "TJ")
    public static let tl = VitaminAsset(name: "TL")
    public static let tm = VitaminAsset(name: "TM")
    public static let tn = VitaminAsset(name: "TN")
    public static let to = VitaminAsset(name: "TO")
    public static let tr = VitaminAsset(name: "TR")
    public static let tt = VitaminAsset(name: "TT")
    public static let tw = VitaminAsset(name: "TW")
    public static let tz = VitaminAsset(name: "TZ")
    public static let ua = VitaminAsset(name: "UA")
    public static let ug = VitaminAsset(name: "UG")
    public static let us = VitaminAsset(name: "US")
    public static let uy = VitaminAsset(name: "UY")
    public static let uz = VitaminAsset(name: "UZ")
    public static let vc = VitaminAsset(name: "VC")
    public static let ve = VitaminAsset(name: "VE")
    public static let vg = VitaminAsset(name: "VG")
    public static let vn = VitaminAsset(name: "VN")
    public static let vu = VitaminAsset(name: "VU")
    public static let ws = VitaminAsset(name: "WS")
    public static let ww = VitaminAsset(name: "WW")
    public static let ye = VitaminAsset(name: "YE")
    public static let za = VitaminAsset(name: "ZA")
    public static let zm = VitaminAsset(name: "ZM")
    public static let zw = VitaminAsset(name: "ZW")
  }
  public enum Logo {
    public static let faviconBlack = VitaminAsset(name: "favicon-black")
    public static let favicon = VitaminAsset(name: "favicon")
    public static let logoOutlined = VitaminAsset(name: "logo-outlined")
    public static let logo = VitaminAsset(name: "logo")
  }
  public enum Payment {
    public static let amazonPay = VitaminAsset(name: "AmazonPay")
    public static let amex = VitaminAsset(name: "Amex")
    public static let applePay = VitaminAsset(name: "ApplePay")
    public static let bvr = VitaminAsset(name: "BVR")
    public static let bancontactPayconiq = VitaminAsset(name: "Bancontact-payconiq")
    public static let bancontact = VitaminAsset(name: "Bancontact")
    public static let belfius = VitaminAsset(name: "Belfius")
    public static let bitcoin = VitaminAsset(name: "Bitcoin")
    public static let bitpay = VitaminAsset(name: "Bitpay")
    public static let cb = VitaminAsset(name: "CB")
    public static let cadhoc = VitaminAsset(name: "Cadhoc")
    public static let cash = VitaminAsset(name: "Cash")
    public static let clickandBuy = VitaminAsset(name: "ClickandBuy")
    public static let dinersClubInternational = VitaminAsset(name: "DinersClubInternational")
    public static let discover = VitaminAsset(name: "Discover")
    public static let dwolla = VitaminAsset(name: "Dwolla")
    public static let eps = VitaminAsset(name: "EPS")
    public static let elo = VitaminAsset(name: "Elo")
    public static let eway = VitaminAsset(name: "Eway")
    public static let giroPay = VitaminAsset(name: "GiroPay")
    public static let googlePay = VitaminAsset(name: "GooglePay")
    public static let ing = VitaminAsset(name: "ING")
    public static let illicado = VitaminAsset(name: "Illicado")
    public static let ingenico = VitaminAsset(name: "Ingenico")
    public static let jcb = VitaminAsset(name: "JCB")
    public static let kbc = VitaminAsset(name: "KBC")
    public static let klarna = VitaminAsset(name: "Klarna")
    public static let mbMultibanco = VitaminAsset(name: "MB-Multibanco")
    public static let mbWay = VitaminAsset(name: "MB-Way")
    public static let mnp = VitaminAsset(name: "MNP")
    public static let maestroFull = VitaminAsset(name: "Maestro Full")
    public static let maestro = VitaminAsset(name: "Maestro")
    public static let masterCardIDCheck = VitaminAsset(name: "MasterCard ID Check")
    public static let mastercardFull = VitaminAsset(name: "Mastercard Full")
    public static let mastercard = VitaminAsset(name: "Mastercard")
    public static let neteller = VitaminAsset(name: "Neteller")
    public static let oneyClassic = VitaminAsset(name: "Oney Classic")
    public static let oney3x = VitaminAsset(name: "Oney3x")
    public static let oney3x4x = VitaminAsset(name: "Oney3x4x")
    public static let oney4x = VitaminAsset(name: "Oney4x")
    public static let payU = VitaminAsset(name: "PayU")
    public static let paylib = VitaminAsset(name: "Paylib")
    public static let paymill = VitaminAsset(name: "Paymill")
    public static let payoneer = VitaminAsset(name: "Payoneer")
    public static let paypal = VitaminAsset(name: "Paypal")
    public static let paysafeCard = VitaminAsset(name: "PaysafeCard")
    public static let pointsPay = VitaminAsset(name: "PointsPay")
    public static let postFinanceCard = VitaminAsset(name: "PostFinanceCard")
    public static let postFinanceEFinance = VitaminAsset(name: "PostFinanceE-Finance")
    public static let postePay = VitaminAsset(name: "PostePay")
    public static let powerPay = VitaminAsset(name: "PowerPay")
    public static let przelewy24 = VitaminAsset(name: "Przelewy24")
    public static let sepa = VitaminAsset(name: "SEPA")
    public static let skrill = VitaminAsset(name: "Skrill")
    public static let spiritOfCadeau = VitaminAsset(name: "Spirit of cadeau")
    public static let stripe = VitaminAsset(name: "Stripe")
    public static let unionPay = VitaminAsset(name: "UnionPay")
    public static let verifone = VitaminAsset(name: "Verifone")
    public static let visaClassic = VitaminAsset(name: "Visa Classic")
    public static let visaElectron = VitaminAsset(name: "Visa Electron")
    public static let webMoney = VitaminAsset(name: "WebMoney")
    public static let westernUnion = VitaminAsset(name: "WesternUnion")
    public static let iDeal = VitaminAsset(name: "iDeal")
  }
  public enum Placeholder {
    public static let landscape = VitaminAsset(name: "landscape")
  }
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

public struct VitaminAsset {
  public fileprivate(set) var name: String

  public var image: UIImage {
    let bundle = BundleToken.bundle
    #if os(iOS) || os(tvOS)
    let resultImage = UIImage(named: name, in: bundle, compatibleWith: nil)
    #elseif os(watchOS)
    let resultImage = UIImage(named: name)
    #endif
    guard let result = resultImage else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }
}

public extension UIImage {
  convenience init?(asset: VitaminAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = BundleToken.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

// swiftlint:disable convenience_type
private final class BundleToken {
  static let bundle: Bundle = {
    #if SWIFT_PACKAGE
    return Bundle.module
    #else
    return Bundle(for: BundleToken.self)
    #endif
  }()
}
// swiftlint:enable convenience_type
