name: Build Pull Request

on:
  pull_request: {}

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - uses: juztcode/pr-updater@1.0.0
        if: ${{ github.head_ref == 'feat/update-icons-sources' }}
        with:
          title: 'feat: update icons sources'
          body: '**Automated Pull Request to update icons.**'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: danielswensson/auto-assign-owner-action@v1
        if: ${{ github.head_ref == 'feat/update-icons-sources' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.head_ref == 'feat/update-icons-sources' }}
        with:
          labels: |
            enhancement 🚀
            icons ✨
          
      - uses: actions/add-to-project@v0.4.0
        if: ${{ github.head_ref == 'feat/update-icons-sources' }}
        with:
          project-url: https://github.com/orgs/Decathlon/projects/3
          github-token: ${{ secrets.API_TOKEN_GITHUB }}

      - uses: juztcode/pr-updater@1.0.0
        if: ${{ github.head_ref == 'feat/update-icons-showcase' }}
        with:
          title: 'feat: update icons showcase'
          body: '**Automated Pull Request to update icons.**'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: danielswensson/auto-assign-owner-action@v1
        if: ${{ github.head_ref == 'feat/update-icons-showcase' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.head_ref == 'feat/update-icons-showcase' }}
        with:
          labels: |
            enhancement 🚀
            icons ✨
          
      - uses: actions/add-to-project@v0.4.0
        if: ${{ github.head_ref == 'feat/update-icons-showcase' }}
        with:
          project-url: https://github.com/orgs/Decathlon/projects/3
          github-token: ${{ secrets.API_TOKEN_GITHUB }}

      - uses: juztcode/pr-updater@1.0.0
        if: ${{ github.head_ref == 'feat/update-assets-sources' }}
        with:
          title: 'feat: update assets sources'
          body: '**Automated Pull Request to update assets.**'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: danielswensson/auto-assign-owner-action@v1
        if: ${{ github.head_ref == 'feat/update-assets-sources' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.head_ref == 'feat/update-assets-sources' }}
        with:
          labels: |
            enhancement 🚀
            assets 🏞
          
      - uses: actions/add-to-project@v0.4.0
        if: ${{ github.head_ref == 'feat/update-assets-sources' }}
        with:
          project-url: https://github.com/orgs/Decathlon/projects/3
          github-token: ${{ secrets.API_TOKEN_GITHUB }}

      - uses: juztcode/pr-updater@1.0.0
        if: ${{ github.head_ref == 'feat/update-assets-showcase' }}
        with:
          title: 'feat: update assets showcase'
          body: '**Automated Pull Request to update assets.**'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: danielswensson/auto-assign-owner-action@v1
        if: ${{ github.head_ref == 'feat/update-assets-showcase' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.head_ref == 'feat/update-assets-showcase' }}
        with:
          labels: |
            enhancement 🚀
            assets 🏞
          
      - uses: actions/add-to-project@v0.4.0
        if: ${{ github.head_ref == 'feat/update-assets-showcase' }}
        with:
          project-url: https://github.com/orgs/Decathlon/projects/3
          github-token: ${{ secrets.API_TOKEN_GITHUB }}