name: Check for Bitrise Label

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  buildshowcase:
    name: Trigger Build with Label
    runs-on: ubuntu-latest

    steps:
      - name: Get the pull request number
        id: pr_number
        run: |
          echo ::set-output name=number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: Send mobile build on bitrise
        if: contains(github.event.pull_request.labels.*.name, 'Ready for Design Review')
        run: |
          curl https://app.bitrise.io/app/${{ secrets.BITRISE_APP_ID }}/build/start.json --data '{
            "hook_info":{
              "type":"bitrise",
              "build_trigger_token":"${{ secrets.BITRISE_BUILD_TRIGGER }}"
            },
            "build_params":{
              "branch":"${{ github.head_ref }}",
              "branch_dest": "${{ github.event.pull_request.base.ref }}",
              "workflow_id":"pull-request",
              "commit_hash":"${{ github.event.pull_request.head.sha }}",
              "pull_request_id": ${{ steps.pr_number.outputs.number }}
            },
            "triggered_by":"curl"
          }'